namespace StockDataScraper
{
    public enum YahooFinanceCategory
    {
        analystestimate,
        balancesheet,
        cashflow,
        dividendhistory,
        historicaldata,
        incomestatement,
        industry,
        isin,
        keystats,
        onvista,
        option_chain,
        option_contract,
        option_contracts,
        options,
        optionsSpecific,
        oquote,
        quant,
        quant2,
        quote,
        quotes,
        quoteslist,
        sectors,
        stocks,
        xchange
    }
}